### ISSUE TITLE
[newdoc] Update repo with new version

### ISSUE THREAD

**Issue by rkratky** [redhat-documentation/tools#31]
@mrksu, could you please update the newdoc version to what's in https://github.com/mrksu/newdoc?

**Comment by pwright** [comment]
+1

**Comment by msuchane** [comment]
@rkratky, I'd like to keep newdoc in a separate repo because it's easier to maintain that way. For example, I use Git tags to mark versions, which apply to the whole repo.

Rather than updating the tools repo with the new code, I've transferred the dedicated newdoc repo to the redhat-documentation organization:

https://github.com/redhat-documentation/newdoc

Is it alright if I close this issue now?

**Comment by rkratky** [comment]
@mrksu, yup. Thanks for moving the repo.
